version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - postgres

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  geoserver:
    image: docker.osgeo.org/geoserver:2.23.1
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=vectortiles
    ports:
      - '8080:8080'
    volumes:
      - geoserver_data:/opt/geoserver_data
    restart: always
volumes:
  postgres_data:
  geoserver_data:
